apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      # Seguridad a nivel de POD
      securityContext:
        runAsNonRoot: {{ .Values.security.runAsNonRoot }}
        runAsUser: {{ .Values.security.runAsUser }}
        fsGroup: {{ .Values.security.fsGroup }}
      
      containers:
        - name: api-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          
          # Seguridad a nivel de CONTENEDOR
          securityContext:
            allowPrivilegeEscalation: {{ .Values.security.allowPrivilegeEscalation }}
            readOnlyRootFilesystem: {{ .Values.security.readOnlyRootFilesystem }}
            capabilities:
              drop: ["ALL"]
          
          ports:
            - containerPort: {{ .Values.service.port }}
          
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          env:
            - name: DB_HOST
              value: {{ .Values.database.host | quote }}
            - name: DB_PORT
              value: {{ .Values.database.port | quote }}
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.existingSecret }}
                  key: DB_NAME
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.existingSecret }}
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.existingSecret }}
                  key: DB_PASSWORD
            # no subir cosas sin contraseña
            - name: UPLOAD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.existingSecret }}
                  key: UPLOAD_API_KEY
            - name: PORT
              value: {{ .Values.service.port | quote }}
            - name: NODE_ENV
              value: "production"

          # Necesario porque el sistema de archivos es read-only
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
      
      volumes:
        - name: tmp-volume
          emptyDir: {}