apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.database.host }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.database.host }}
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.existingSecret }}
                  key: DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.existingSecret }}
                  key: DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.existingSecret }}
                  key: DB_PASSWORD
          ports:
            - containerPort: {{ .Values.database.port }}
          volumeMounts:
            - name: postgredb
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: {{ .Values.database.host }}-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.host }}
spec:
  selector:
    app: postgres
  ports:
    - port: {{ .Values.database.port }}
      targetPort: {{ .Values.database.port }}