apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.database.host }}
spec:
  serviceName: {{ .Values.database.host }}
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.database.image }}
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.existingSecret }}
                  key: DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.existingSecret }}
                  key: DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.existingSecret }}
                  key: DB_PASSWORD
          ports:
            - containerPort: {{ .Values.database.port }}
          volumeMounts:
            - name: postgredb
              mountPath: /var/lib/postgresql/data
  # Esta sección reemplaza al PersistentVolumeClaim estático anterior
  volumeClaimTemplates:
    - metadata:
        name: postgredb
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi # Ajusta según necesidad
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.host }}
spec:
  selector:
    app: postgres
  ports:
    - port: {{ .Values.database.port }}
      targetPort: {{ .Values.database.port }}