replicaCount: 1

image:
  repository: uzbuzbiz/api-backend
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: public
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: api.uzbuzbiz.es
      paths:
        - path: /
          pathType: Prefix
          isApi: true # Para que apunte al servicio de la API de Helm
    - host: uzbuzbiz.es
      paths:
        - path: /
          pathType: Prefix
          serviceName: frontend-service
          servicePort: 80
    - host: jenkins.uzbuzbiz.es
      paths:
        - path: /
          pathType: Prefix
          serviceName: jenkins
          servicePort: 8080
  tls:
    - secretName: api-uzbuzbiz-tls
      hosts:
        - api.uzbuzbiz.es
    - secretName: uzbuzbiz-tls
      hosts:
        - uzbuzbiz.es
    - secretName: jenkins-tls
      hosts:
        - jenkins.uzbuzbiz.es

database:
  image: "postgres:16"
  host: "postgres-service"
  port: 5432
  existingSecret: "backend-db-secrets"

security:
  runAsUser: 1000
  fsGroup: 1000
  runAsNonRoot: true
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "300m"